//! GENERATED by ggen. Tool schemas manufacture intents; they grant no authority.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct McpToolSchema { pub name: &'static str, pub consequence_class: &'static str }

pub const MCP_TOOLS: &[McpToolSchema] = &[
McpToolSchema { name: "chatgptgym.inspect-capability-catalog", consequence_class: "Read" },
McpToolSchema { name: "chatgptgym.inspect-environment", consequence_class: "Read" },
McpToolSchema { name: "chatgptgym.reset-simulation", consequence_class: "Do" },
McpToolSchema { name: "chatgptgym.simulate-capability", consequence_class: "Do" },
];

pub fn lookup_mcp_tool(name: &str) -> Option<&'static McpToolSchema> {
    MCP_TOOLS.iter().find(|tool| tool.name == name)
}
