//! GENERATED by ggen from ChatGPTGym's admitted capability graph. Do not edit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Operation { pub id: &'static str, pub consequence_class: &'static str }

pub const OPERATIONS: &[Operation] = &[
Operation { id: "inspect-capability-catalog", consequence_class: "Read" },
Operation { id: "inspect-environment", consequence_class: "Read" },
Operation { id: "reset-simulation", consequence_class: "Do" },
Operation { id: "simulate-capability", consequence_class: "Do" },
];

pub fn lookup_operation(id: &str) -> Option<&'static Operation> {
    OPERATIONS.iter().find(|op| op.id == id)
}
